# Generated by Django 4.2.3 on 2023-07-06 05:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wh_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='warehouseorder',
            name='store_account',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='wh_app.storeaccount'),
        ),
    ]
